Repository Requisitos-de-Software/2019.2-Wire, pull requests merged in 2019-09, with the labels that each got.

#9 #1 Rich Pictures
  docs/.DS_Store
  docs/assets/.DS_Store
  docs/assets/img/.DS_Store
  docs/pre_rastreabilidade/pre_rastreabilidade.md
  docs/rich_picture/.DS_Store
  docs/rich_picture/images/.DS_Store
  docs/rich_picture/images/Gabriel.jpg
  docs/rich_picture/images/Guilherme.jpg
  docs/rich_picture/images/Iuri.jpg
  docs/rich_picture/images/Joao.png
  docs/rich_picture/images/Lucas.jpg
  docs/rich_picture/rich_picture.md
  index.html
Labels: Ponto de Controle 1, Pré-Rastreabilidade, documentation

#10 Add policies of branches and pull requests
  docs/policies/branches.md
  docs/policies/policies.md
  docs/policies/pull_requests.md
Labels: Pré-Rastreabilidade, documentation

#13 #7 Página de Metodologia
  _sidebar.md
  docs/assets/img/product/methodoly_pictures/drive.png
  docs/assets/img/product/methodoly_pictures/hangouts.png
  docs/assets/img/product/methodoly_pictures/telegram.png
  docs/assets/img/product/methodoly_pictures/telegram2.png
  docs/assets/img/product/methodoly_pictures/wire.png
  docs/assets/img/product/methodoly_pictures/zenhub.png
  docs/methodology/methodology.md
Labels: Pré-Rastreabilidade, documentation

#14 Troca estrutura do docsify
  .DS_Store
  docs/.DS_Store
  docs/README.md
  docs/_coverpage.md
  docs/_sidebar.md
  docs/docs/.DS_Store
  docs/docs/assets/.DS_Store
  docs/docs/assets/css/home.css
  docs/docs/assets/img/.DS_Store
  docs/docs/assets/img/product/.DS_Store
  docs/docs/assets/img/product/methodoly_pictures/drive.png
  docs/docs/assets/img/product/methodoly_pictures/hangouts.png
  docs/docs/assets/img/product/methodoly_pictures/telegram.png
  docs/docs/assets/img/product/methodoly_pictures/telegram2.png
  docs/docs/assets/img/product/methodoly_pictures/wire.png
  docs/docs/assets/img/product/methodoly_pictures/zenhub.png
  docs/docs/assets/img/product/time/caio.jpg
  docs/docs/assets/img/product/time/gabriel.jpg
  docs/docs/assets/img/product/time/guilherme.jpg
  docs/docs/assets/img/product/time/iuri.jpg
  docs/docs/assets/img/product/time/joao_pedro.jpg
  docs/docs/assets/img/product/time/lucas.jpg
  docs/docs/assets/img/product/wire/.DS_Store
  docs/docs/assets/img/product/wire/logo.jpg
  docs/docs/assets/img/product/wire/logo2.jpg
  docs/docs/intro.md
  docs/docs/methodology/methodology.md
  docs/docs/policies/branches.md
  docs/docs/policies/commits.md
  docs/docs/policies/issues.md
  docs/docs/policies/policies.md
  docs/docs/policies/pull_requests.md
  docs/docs/pre_rastreabilidade/pre_rastreabilidade.md
  docs/docs/rich_picture/.DS_Store
  docs/docs/rich_picture/images/.DS_Store
  docs/docs/rich_picture/images/Caio.png
  docs/docs/rich_picture/images/Gabriel.jpg
  docs/docs/rich_picture/images/Guilherme.jpg
  docs/docs/rich_picture/images/Iuri.jpg
  docs/docs/rich_picture/images/Joao.png
  docs/docs/rich_picture/images/Lucas.jpg
  docs/docs/rich_picture/rich_picture.md
  docs/index.html
  docs/pull_request_template.md
Labels: documentation

#16 Adiciona sobre a Disciplina
  README.md
  docs/README.md
  docs/_sidebar.md
  docs/docs/assets/img/product/wire/logo3.jpg
  docs/docs/discipline/about_discipline.md
  docs/docs/elicitation/elicitation.md
  docs/docs/elicitation/introspeccao.md
  docs/docs/pre_rastreabilidade/pre_rastreabilidade.md
  docs/index.html
Labels: Elicitação, Ponto de Controle 2

#21 15 - Elicitação de Requisitos - Entrevista
  README.md
  docs/README.md
  docs/_sidebar.md
  docs/docs/discipline/about_discipline.md
  docs/docs/elicitation/elicitation.md
  docs/docs/elicitation/entrevista.md
  docs/docs/elicitation/introspeccao.md
Labels: Ponto de Controle 2, documentation

#20 #19 Adicionar divisórias nas colunas das tabelas.
  docs/docs/assets/css/table.css
  docs/docs/discipline/about_discipline.md
  docs/docs/policies/policies.md
Labels: docsify

#22 HOTFIX #19 Corrigir erros em alguns arquivos e adicionar divisória para todas as tabelas
  docs/docs/elicitation/entrevista.md
  docs/docs/methodology/methodology.md
  docs/docs/policies/branches.md
  docs/docs/policies/commits.md
  docs/docs/policies/issues.md
  docs/docs/policies/policies.md
  docs/docs/policies/pull_requests.md
Labels: Melhoria

#23 Adiciona tópicos na tela de Introspecção
  docs/docs/elicitation/introspeccao.md
Labels: Elicitação, Ponto de Controle 2

#24 #18 - Adiciona elicitação 5W2H.
  docs/_sidebar.md
  docs/docs/elicitation/5W2H.md
  docs/docs/elicitation/elicitation.md
  docs/docs/elicitation/entrevista.md
Labels: Ponto de Controle 2, docsify

#26 #25 - Página com resultados do questionário
  docs/docs/assets/img/forms/.DS_Store
  docs/docs/assets/img/forms/1.png
  docs/docs/assets/img/forms/10.png
  docs/docs/assets/img/forms/2.png
  docs/docs/assets/img/forms/3.png
  docs/docs/assets/img/forms/4.png
  docs/docs/assets/img/forms/5.png
  docs/docs/assets/img/forms/6-1.png
  docs/docs/assets/img/forms/6.png
  docs/docs/assets/img/forms/7-1.png
  docs/docs/assets/img/forms/7.png
  docs/docs/assets/img/forms/8-1.png
  docs/docs/assets/img/forms/8.png
  docs/docs/assets/img/forms/9-1.png
  docs/docs/assets/img/forms/9.png
  docs/docs/elicitation/5W2H.md
  docs/docs/elicitation/elicitation.md
  docs/docs/elicitation/forms.md
Labels: Ponto de Controle 2, docsify, documentation

#29 Página de Priorização
  docs/_sidebar.md
  docs/docs/assets/css/table.css
  docs/docs/discipline/about_discipline.md
  docs/docs/prioritization/FTF.md
  docs/docs/prioritization/prioritization.md
  docs/docs/rich_picture/rich_picture.md
Labels: Ponto de Controle 2, docsify

#30 #12 Elicitação de Requisitos - Questionário
  docs/docs/assets/img/forms/Question1.png
  docs/docs/assets/img/forms/Question10-1.png
  docs/docs/assets/img/forms/Question10.png
  docs/docs/assets/img/forms/Question11.png
  docs/docs/assets/img/forms/Question12.png
  docs/docs/assets/img/forms/Question13.png
  docs/docs/assets/img/forms/Question14.png
  docs/docs/assets/img/forms/Question15.png
  docs/docs/assets/img/forms/Question16.png
  docs/docs/assets/img/forms/Question17.png
  docs/docs/assets/img/forms/Question2.png
  docs/docs/assets/img/forms/Question3.png
  docs/docs/assets/img/forms/Question4.png
  docs/docs/assets/img/forms/Question5.png
  docs/docs/assets/img/forms/Question6.png
  docs/docs/assets/img/forms/Question7-1.png
  docs/docs/assets/img/forms/Question7.png
  docs/docs/assets/img/forms/Question8-1.png
  docs/docs/assets/img/forms/Question8.png
  docs/docs/assets/img/forms/Question9-1.png
  docs/docs/assets/img/forms/Question9.png
  docs/docs/elicitation/forms.md
Labels: Elicitação, Ponto de Controle 2, docsify, documentation

#31 Adiociona priorização MoSCoW
  docs/docs/elicitation/introspeccao.md
  docs/docs/prioritization/moscow.md
  docs/docs/prioritization/prioritization.md
Labels: Elicitação, Ponto de Controle 2

#33 Adiciona versionamento
  docs/docs/elicitation/5W2H.md
  docs/docs/elicitation/entrevista.md
  docs/docs/elicitation/introspeccao.md
  docs/docs/elicitation/storytelling.md
  docs/docs/prioritization/FTF.md
  docs/docs/prioritization/moscow.md
  docs/docs/rich_picture/rich_picture.md
  docs/index.html
Labels: documentation

#34 Adiciona Matriz de Relação
  docs/docs/assets/img/product/elicitation/rf_matrix.jpg
  docs/docs/assets/img/product/elicitation/rnf_matrix.png
  docs/docs/elicitation/elicitation.md
  docs/docs/elicitation/matrix.md
Labels: documentation

#39 Modelagem de Requisitos - Casos de Uso
  docs/_sidebar.md
  docs/docs/assets/img/modeling/user_cases_diagram.jpg
  docs/docs/modeling/modeling.md
  docs/docs/modeling/user_cases.md
Labels: Modelagem de Requisitos, Ponto de Controle 3, documentation
