Repository Requisitos-de-Software/2019.2-Wire, pull requests merged in 2019-10, with the labels that each got.

#40 36 - Léxicos(Verbos, estados e objetos)
  docs/docs/modeling/lexicons.md
  docs/docs/modeling/lexicos/objects.md
  docs/docs/modeling/lexicos/states.md
  docs/docs/modeling/lexicos/verbs.md
  docs/docs/modeling/modeling.md
Labels: Modelagem de Requisitos, Ponto de Controle 3, documentation

#41 35- Cenários
  docs/docs/modeling/backdrops.md
  docs/docs/modeling/modeling.md
  docs/docs/modeling/scenarios.md
Labels: Ponto de Controle 3, documentation

#42 Adiciona modelagem de Especificação Suplementar
  docs/docs/modeling/modeling.md
  docs/docs/modeling/supplementary_specifications.md
Labels: Modelagem de Requisitos, Ponto de Controle 3

#49 Melhoria no Layout da página de Cenários.
  docs/docs/assets/css/table.css
  docs/docs/modeling/modeling.md
  docs/docs/modeling/scenarios.md
Labels: Melhoria, Modelagem de Requisitos

#53 43 - Subir todos os requisitos
  docs/docs/elicitation/elicitation.md
  docs/docs/elicitation/matrix.md
Labels: Elicitação, Melhoria, docsify, documentation

#57 Modelagem Ágil - Backlog
  docs/_sidebar.md
  docs/docs/assets/css/backlog_image.css
  docs/docs/assets/img/backlog/1.png
  docs/docs/assets/img/backlog/2.png
  docs/docs/assets/img/backlog/BacklogDiagram.png
  docs/docs/assets/img/backlog/RQS.png
  docs/docs/assets/img/backlog/RQS2.jpg
  docs/docs/assets/img/backlog/RQS3.jpg
  docs/docs/elicitation/matrix.md
  docs/docs/intro.md
  docs/docs/modeling/backdrops.md
  docs/docs/modeling/backlog.md
  docs/docs/modeling/modeling.md
Labels: Modelagem de Requisitos, Ponto de Controle 4, documentation

#58 Corrige localização do NFR
  docs/docs/modeling/modeling.md
Labels: Melhoria, Ponto de Controle 4, docsify

#60 #59 - Adding NFR Framework verification
  docs/_sidebar.md
  docs/docs/verification/NFR/NFR.md
  docs/docs/verification/NFR/NFR_efficiency_verify.md
  docs/docs/verification/NFR/NFR_reliability_verify.md
  docs/docs/verification/NFR/NFR_usability_verify.md
  docs/docs/verification/verification.md
Labels: Ponto de Controle 5, Verficação, documentation
