Repository Requisitos-de-Software/2019.2-Wire, pull requests merged in 2019-11, with the labels that each got.

#67 Adição da verificação da especificação suplementar
  .DS_Store
  docs/.DS_Store
  docs/docs/.DS_Store
  docs/docs/assets/.DS_Store
  docs/docs/assets/img/.DS_Store
  docs/docs/assets/img/forms/.DS_Store
  docs/docs/assets/img/product/.DS_Store
  docs/docs/assets/img/product/wire/.DS_Store
  docs/docs/modeling/supplementary_specifications.md
  docs/docs/rich_picture/.DS_Store
  docs/docs/rich_picture/images/.DS_Store
  docs/docs/verification/supplementary_specification/supplementary_specification.md
  docs/docs/verification/verification.md
Labels: Ponto de Controle 5, Verficação, documentation

#70 Verificação - Casos de Uso
  docs/docs/verification/use_cases/1.png
  docs/docs/verification/use_cases/10.png
  docs/docs/verification/use_cases/2.png
  docs/docs/verification/use_cases/3.png
  docs/docs/verification/use_cases/4.png
  docs/docs/verification/use_cases/5.png
  docs/docs/verification/use_cases/6.png
  docs/docs/verification/use_cases/7.png
  docs/docs/verification/use_cases/8.png
  docs/docs/verification/use_cases/9.png
  docs/docs/verification/use_cases/use_cases_verification.md
  docs/docs/verification/use_cases/user_cases_verification.jpg
  docs/docs/verification/verification.md
Labels: Ponto de Controle 5, Validação

#71 69 - Verificação do Ágil
  docs/docs/assets/img/verification/agile/CHECKLIST.png
  docs/docs/assets/img/verification/agile/agileverification.png
  docs/docs/assets/img/verification/agile/img1.png
  docs/docs/assets/img/verification/agile/img10.png
  docs/docs/assets/img/verification/agile/img11.png
  docs/docs/assets/img/verification/agile/img12.png
  docs/docs/assets/img/verification/agile/img13.png
  docs/docs/assets/img/verification/agile/img14.png
  docs/docs/assets/img/verification/agile/img15.png
  docs/docs/assets/img/verification/agile/img2.png
  docs/docs/assets/img/verification/agile/img3.png
  docs/docs/assets/img/verification/agile/img4.png
  docs/docs/assets/img/verification/agile/img5.png
  docs/docs/assets/img/verification/agile/img6.png
  docs/docs/assets/img/verification/agile/img7.png
  docs/docs/assets/img/verification/agile/img8.png
  docs/docs/assets/img/verification/agile/img9.png
  docs/docs/verification/Agile/agile.md
  docs/docs/verification/verification.md
Labels: Ponto de Controle 5, Verficação

#73 Verificação dos Léxicos
  docs/_sidebar.md
  docs/docs/validation/email/email.md
  docs/docs/validation/validation.md
  docs/docs/verification/lexico/lexicoMenu.md
  docs/docs/verification/lexico/lexicoObject.md
  docs/docs/verification/lexico/lexicoVerbs.md
  docs/docs/verification/lexico/objectFix.md
  docs/docs/verification/verification.md
Labels: Ponto de Controle 5, Verficação, documentation

#74 HOTFIX - Corrige referencias da verificação dos casos de uso
  docs/docs/verification/use_cases/use_cases_verification.md
Labels: Melhoria, documentation

#82 Matriz de pós-rastreabilidade Backward From
  docs/docs/assets/css/table.css
  docs/docs/post_traceability/backward_from.md
  docs/docs/post_traceability/post_rastreability.md
Labels: Ponto de Controle 6, documentation

#87 Refatorar cenários
  docs/docs/modeling/lexicos/objects.md
  docs/docs/modeling/scenarios.md
Labels: Apresentação Final, Melhoria, documentation

#85 #78 refatorar backlog
  docs/docs/modeling/backlog.md
  docs/docs/post_traceability/forward_from.md
  docs/docs/post_traceability/user_stories.md
Labels: Apresentação Final, Melhoria, documentation
